spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library-shop?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: toor
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false