cors:
  originPatterns: http://localhost:3000,http://localhost:8080
file:
  upload-dir: /your-path
security:
  jwt:
    token:
      secret-key: 44rtx1
      expire-length: 3600000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library-shop?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: toor
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
spring-doc:
  paths-to-match:
    - /api/**/v1/**
    - /api/**/v2/**
    - /auth/**
  swagger-ui:
    use-root-path: true